name: CI/CD Pipeline for Node.js Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/app-1"
          port: 22 # Ensure correct SSH port
          debug: true

      - name: Restart application
        run: |
          ssh -o StrictHostKeyChecking=no -i /github/home/.ssh/id_rsa_github_actions ubuntu@${{ secrets.PUBLIC_IP }} << 'EOF'
            cd /app-1
            npm install --production  # Install production dependencies
            pm2 restart my-app1 || pm2 start index.js --name my-app1  # Adjust index.js to your main file
          EOF
